apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
commonAnnotations:
  grafana_folder: "istio"

configMapGenerator:
  - files:
      - dashboards/pilot-dashboard.json
    name: dashboard-pilot
  - files:
      - dashboards/istio-workload-dashboard.json
    name: dashboard-istio-workload
  - files:
      - dashboards/istio-service-dashboard.json
    name: dashboard-istio-service
  - files:
      - dashboards/istio-performance-dashboard.json
    name: dashboard-istio-performance
  - files:
      - dashboards/istio-mesh-dashboard.json
    name: dashboard-istio-mesh
  - files:
      - dashboards/istio-extension-dashboard.json
    name: dashboard-istio-extension
